---

- name: "Test playbook"
  hosts:
    - localhost
  gather_facts: true
  tasks:

    - name: "Print message"
      debug:
        msg: "Hello, world from ansible!"

    - name: "Print distribution name"
      debug:
        var: ansible_distribution

    - name: "Custom playbook action"
      debug:
        msg: "Doing some custom action"
